// Code generated from the curated handmade CPE dataset plus hand-added
// overrides; see docs/extract-fortinet-csaf-cvrf.md. Maps a Fortinet product
// name (as it appears in CSAF product nodes and CVRF "Product Name" branches)
// to its CPE 2.3 formatted string with a wildcard version.
package product

var nameToCPE = map[string]string{
	"AV Engine":                            "cpe:2.3:a:fortinet:antivirus_engine:*:*:*:*:*:*:*:*",
	"AscenLink":                            "cpe:2.3:o:fortinet:ascenlink:*:*:*:*:*:*:*:*",
	"FortiADC":                             "cpe:2.3:o:fortinet:fortiadc:*:*:*:*:*:*:*:*",
	"FortiADCManager":                      "cpe:2.3:a:fortinet:fortiadc_manager:*:*:*:*:*:*:*:*",
	"FortiAIOps":                           "cpe:2.3:a:fortinet:fortiaiops:*:*:*:*:*:*:*:*",
	"FortiAP":                              "cpe:2.3:o:fortinet:fortiap:*:*:*:*:*:*:*:*",
	"FortiAP-C":                            "cpe:2.3:o:fortinet:fortiap-c:*:*:*:*:*:*:*:*",
	"FortiAP-S":                            "cpe:2.3:o:fortinet:fortiap-s:*:*:*:*:*:*:*:*",
	"FortiAP-U":                            "cpe:2.3:o:fortinet:fortiap-u:*:*:*:*:*:*:*:*",
	"FortiAP-W2":                           "cpe:2.3:o:fortinet:fortiap-w2:*:*:*:*:*:*:*:*",
	"FortiAnalyzer":                        "cpe:2.3:o:fortinet:fortianalyzer:*:*:*:*:*:*:*:*",
	"FortiAnalyzer Cloud":                  "cpe:2.3:a:fortinet:fortianalyzer_cloud:*:*:*:*:*:*:*:*",
	"FortiAnalyzer-BigData":                "cpe:2.3:o:fortinet:fortianalyzer-bigdata:*:*:*:*:*:*:*:*",
	"FortiAuthenticator":                   "cpe:2.3:o:fortinet:fortiauthenticator:*:*:*:*:*:*:*:*",
	"FortiAuthenticator OutlookAgent":      "cpe:2.3:a:fortinet:fortiauthenticator:*:*:*:*:*:*:*:*",
	"FortiCache":                           "cpe:2.3:o:fortinet:forticache:*:*:*:*:*:*:*:*",
	"FortiCamera":                          "cpe:2.3:o:fortinet:forticamera:*:*:*:*:*:*:*:*",
	"FortiClientAndroid":                   "cpe:2.3:a:fortinet:forticlient:*:*:*:*:*:*:*:*",
	"FortiClientEMS":                       "cpe:2.3:a:fortinet:forticlient_enterprise_management_server:*:*:*:*:*:*:*:*",
	"FortiClientEMS Cloud":                 "cpe:2.3:a:fortinet:forticlient_enterprise_management_server_cloud:*:*:*:*:*:*:*:*",
	"FortiClientLinux":                     "cpe:2.3:a:fortinet:forticlient:*:*:*:*:*:*:*:*",
	"FortiClientMac":                       "cpe:2.3:a:fortinet:forticlient:*:*:*:*:*:*:*:*",
	"FortiClientWindows":                   "cpe:2.3:a:fortinet:forticlient:*:*:*:*:*:*:*:*",
	"FortiClientiOS":                       "cpe:2.3:a:fortinet:forticlient:*:*:*:*:*:*:*:*",
	"FortiConverter":                       "cpe:2.3:a:fortinet:forticonverter:*:*:*:*:*:*:*:*",
	"FortiDB":                              "cpe:2.3:o:fortinet:fortidb:*:*:*:*:*:*:*:*",
	"FortiDDoS":                            "cpe:2.3:o:fortinet:fortiddos:*:*:*:*:*:*:*:*",
	"FortiDDoS-CM":                         "cpe:2.3:a:fortinet:fortiddos-cm:*:*:*:*:*:*:*:*",
	"FortiDDoS-F":                          "cpe:2.3:o:fortinet:fortiddos-f:*:*:*:*:*:*:*:*",
	"FortiDLP":                             "cpe:2.3:a:fortinet:fortidlp:*:*:*:*:*:*:*:*",
	"FortiDeceptor":                        "cpe:2.3:o:fortinet:fortideceptor:*:*:*:*:*:*:*:*",
	"FortiEDR":                             "cpe:2.3:a:fortinet:fortiedr:*:*:*:*:*:*:*:*",
	"FortiEDR CollectorWindows":            "cpe:2.3:a:fortinet:fortiedr:*:*:*:*:*:*:*:*",
	"FortiEDR Manager":                     "cpe:2.3:a:fortinet:fortiedr_manager:*:*:*:*:*:*:*:*",
	"FortiExtender":                        "cpe:2.3:o:fortinet:fortiextender:*:*:*:*:*:*:*:*",
	"FortiFone":                            "cpe:2.3:o:fortinet:fortifone:*:*:*:*:*:*:*:*",
	"FortiGuest":                           "cpe:2.3:a:fortinet:fortiguest:*:*:*:*:*:*:*:*",
	"FortiIsolator":                        "cpe:2.3:o:fortinet:fortiisolator:*:*:*:*:*:*:*:*",
	"FortiMail":                            "cpe:2.3:o:fortinet:fortimail:*:*:*:*:*:*:*:*",
	"FortiManager":                         "cpe:2.3:o:fortinet:fortimanager:*:*:*:*:*:*:*:*",
	"FortiManager Cloud":                   "cpe:2.3:a:fortinet:fortimanager_cloud:*:*:*:*:*:*:*:*",
	"FortiNAC":                             "cpe:2.3:o:fortinet:fortinac:*:*:*:*:*:*:*:*",
	"FortiNAC-F":                           "cpe:2.3:o:fortinet:fortinac-f:*:*:*:*:*:*:*:*",
	"FortiNDR":                             "cpe:2.3:o:fortinet:fortindr:*:*:*:*:*:*:*:*",
	"FortiOS":                              "cpe:2.3:o:fortinet:fortios:*:*:*:*:*:*:*:*",
	"FortiOS-6K7K":                         "cpe:2.3:o:fortinet:fortios-6k7k:*:*:*:*:*:*:*:*",
	"FortiPAM":                             "cpe:2.3:a:fortinet:fortipam:*:*:*:*:*:*:*:*",
	"FortiPortal":                          "cpe:2.3:a:fortinet:fortiportal:*:*:*:*:*:*:*:*",
	"FortiPresence":                        "cpe:2.3:a:fortinet:fortipresence:*:*:*:*:*:*:*:*",
	"FortiProxy":                           "cpe:2.3:o:fortinet:fortiproxy:*:*:*:*:*:*:*:*",
	"FortiRecorder":                        "cpe:2.3:o:fortinet:fortirecorder:*:*:*:*:*:*:*:*",
	"FortiSASE":                            "cpe:2.3:a:fortinet:fortisase:*:*:*:*:*:*:*:*",
	"FortiSIEM":                            "cpe:2.3:o:fortinet:fortisiem:*:*:*:*:*:*:*:*",
	"FortiSOAR Agent Communication Bridge": "cpe:2.3:a:fortinet:fortisoar_agent_communication_bridge:*:*:*:*:*:*:*:*",
	"FortiSOAR PaaS":                       "cpe:2.3:a:fortinet:fortisoar:*:*:*:*:*:*:*:*",
	"FortiSOAR on-premise":                 "cpe:2.3:a:fortinet:fortisoar:*:*:*:*:*:*:*:*",
	"FortiSRA":                             "cpe:2.3:a:fortinet:fortisra:*:*:*:*:*:*:*:*",
	"FortiSandbox":                         "cpe:2.3:o:fortinet:fortisandbox:*:*:*:*:*:*:*:*",
	"FortiSandbox Cloud":                   "cpe:2.3:a:fortinet:fortisandbox_cloud:*:*:*:*:*:*:*:*",
	"FortiSandbox PaaS":                    "cpe:2.3:a:fortinet:fortisandbox_paas:*:*:*:*:*:*:*:*",
	"FortiSwitch":                          "cpe:2.3:o:fortinet:fortiswitch:*:*:*:*:*:*:*:*",
	"FortiSwitchAXFixed":                   "cpe:2.3:a:fortinet:fortiswitchaxfixed:*:*:*:*:*:*:*:*",
	"FortiSwitchManager":                   "cpe:2.3:o:fortinet:fortiswitchmanager:*:*:*:*:*:*:*:*",
	"FortiTester":                          "cpe:2.3:o:fortinet:fortitester:*:*:*:*:*:*:*:*",
	"FortiTokenAndroid":                    "cpe:2.3:a:fortinet:fortitoken_mobile:*:*:*:*:*:*:*:*",
	"FortiTokenIOS":                        "cpe:2.3:a:fortinet:fortitoken_mobile:*:*:*:*:*:*:*:*",
	"FortiTokenMobileWP":                   "cpe:2.3:a:fortinet:fortitoken_mobile:*:*:*:*:*:*:*:*",
	"FortiVoice":                           "cpe:2.3:o:fortinet:fortivoice:*:*:*:*:*:*:*:*",
	"FortiVoiceUCDesktop":                  "cpe:2.3:a:fortinet:fortivoice_cloud_unified_communications_desktop:*:*:*:*:*:*:*:*",
	"FortiWAN":                             "cpe:2.3:o:fortinet:fortiwan:*:*:*:*:*:*:*:*",
	"FortiWAN-Manager":                     "cpe:2.3:a:fortinet:fortiwan_manager:*:*:*:*:*:*:*:*",
	"FortiWLC":                             "cpe:2.3:o:fortinet:fortiwlc:*:*:*:*:*:*:*:*",
	"FortiWLM":                             "cpe:2.3:o:fortinet:fortiwlm:*:*:*:*:*:*:*:*",
	"FortiWeb":                             "cpe:2.3:o:fortinet:fortiweb:*:*:*:*:*:*:*:*",
	"FortiWebManager":                      "cpe:2.3:a:fortinet:fortiweb_manager:*:*:*:*:*:*:*:*",
	"IPS Engine":                           "cpe:2.3:a:fortinet:fortios_ips_engine:*:*:*:*:*:*:*:*",
	"Meru AP":                              "cpe:2.3:a:fortinet:meru:*:*:*:*:*:*:*:*",
}
