package source

import (
	"cmp"
	"slices"
)

type SourceID string

type Source struct {
	ID   SourceID `json:"id,omitempty"`
	Raws []string `json:"raws,omitempty"`
}

const (
	AlmaErrata            SourceID = "alma-errata"
	AlmaOSV               SourceID = "alma-osv"
	AlmaOVAL              SourceID = "alma-oval"
	AlpineOSV             SourceID = "alpine-osv"
	AlpineSecDB           SourceID = "alpine-secdb"
	AltOVAL               SourceID = "alt-oval"
	Amazon                SourceID = "amazon"
	AndroidOSV            SourceID = "android-osv"
	AnolisOVAL            SourceID = "anolis-oval"
	Arch                  SourceID = "arch"
	Attack                SourceID = "attack"
	AzureOVAL             SourceID = "azure-oval"
	BitnamiOSV            SourceID = "bitnami-osv"
	Capec                 SourceID = "capec"
	CargoDB               SourceID = "cargo-db"
	CargoGHSA             SourceID = "cargo-ghsa"
	CargoOSV              SourceID = "cargo-osv"
	ChainguardOSV         SourceID = "chainguard-osv"
	ChainguardSecDB       SourceID = "chainguard-secdb"
	CISAKEV               SourceID = "cisa-kev"
	CiscoCSAF             SourceID = "cisco-csaf"
	CiscoCVRF             SourceID = "cisco-cvrf"
	CiscoJSON             SourceID = "cisco-json"
	ComposerDB            SourceID = "composer-db"
	ComposerGHSA          SourceID = "composer-ghsa"
	ComposerGLSA          SourceID = "composer-glsa"
	ComposerOSV           SourceID = "composer-osv"
	ConanGLSA             SourceID = "conan-glsa"
	CWE                   SourceID = "cwe"
	DebianOSV             SourceID = "debian-osv"
	DebianOVAL            SourceID = "debian-oval"
	DebianSecurityTracker SourceID = "debian-security-tracker"
	Echo                  SourceID = "echo"
	EndoflifeDateAPI      SourceID = "endoflife-date-api"
	EndoflifeDateProducts SourceID = "endoflife-date-products"
	EOL                   SourceID = "eol"
	EPSS                  SourceID = "epss"
	ErlangGHSA            SourceID = "erlang-ghsa"
	ErlangOSV             SourceID = "erlang-osv"
	ExploitExploitDB      SourceID = "exploit-exploitdb"
	ExploitGitHub         SourceID = "exploit-github"
	ExploitInTheWild      SourceID = "exploit-inthewild"
	ExploitTrickest       SourceID = "exploit-trickest"
	FedoraAPI             SourceID = "fedora-api"
	Fortinet              SourceID = "fortinet"
	FortinetCVRF          SourceID = "fortinet-cvrf"
	FreeBSD               SourceID = "freebsd"
	Gentoo                SourceID = "gentoo"
	GitHubActionsOSV      SourceID = "github-actions-osv"
	GitOSV                SourceID = "git-osv"
	GolangDB              SourceID = "golang-db"
	GolangGHSA            SourceID = "golang-ghsa"
	GolangGLSA            SourceID = "golang-glsa"
	GolangOSV             SourceID = "golang-osv"
	GolangVulnDB          SourceID = "golang-vulndb"
	HaskellDB             SourceID = "haskell-db"
	HaskellOSV            SourceID = "haskell-osv"
	JVNFeedDetail         SourceID = "jvn-feed-detail"
	JVNFeedProduct        SourceID = "jvn-feed-product"
	JVNFeedRSS            SourceID = "jvn-feed-rss"
	K8sJSON               SourceID = "k8s-json"
	K8sOSV                SourceID = "k8s-osv"
	LinuxOSV              SourceID = "linux-osv"
	MageiaOSV             SourceID = "mageia-osv"
	MavenGHSA             SourceID = "maven-ghsa"
	MavenGLSA             SourceID = "maven-glsa"
	MavenOSV              SourceID = "maven-osv"
	MinimosSecDB          SourceID = "minimos-secdb"
	MitreCVRF             SourceID = "mitre-cvrf"
	MitreV4               SourceID = "mitre-v4"
	MitreV5               SourceID = "mitre-v5"
	Metasploit            SourceID = "metasploit"
	NetBSD                SourceID = "netbsd"
	NpmDB                 SourceID = "npm-db"
	NpmGHSA               SourceID = "npm-ghsa"
	NpmGLSA               SourceID = "npm-glsa"
	NpmOSV                SourceID = "npm-osv"
	NucleiRepository      SourceID = "nuclei-repository"
	NugetGHSA             SourceID = "nuget-ghsa"
	NugetGLSA             SourceID = "nuget-glsa"
	NugetOSV              SourceID = "nuget-osv"
	NVDAPICPE             SourceID = "nvd-api-cpe"
	NVDAPICPEMatch        SourceID = "nvd-api-cpematch"
	NVDAPICVE             SourceID = "nvd-api-cve"
	NVDFeedCPEv1          SourceID = "nvd-feed-cpe-v1"
	NVDFeedCPEMATCHv1     SourceID = "nvd-feed-cpematch-v1"
	NVDFeedCVEv1          SourceID = "nvd-feed-cve-v1"
	NVDFeedCPEv2          SourceID = "nvd-feed-cpe-v2"
	NVDFeedCPEMATCHv2     SourceID = "nvd-feed-cpematch-v2"
	NVDFeedCVEv2          SourceID = "nvd-feed-cve-v2"
	OpenEulerCSAF         SourceID = "openeuler-csaf"
	OpenEulerCVRF         SourceID = "openeuler-cvrf"
	Oracle                SourceID = "oracle"
	OSSFuzzOSV            SourceID = "oss-fuzz-osv"
	PaloAltoCSAF          SourceID = "paloalto-csaf"
	PaloAltoJSON          SourceID = "paloalto-json"
	PaloAltoList          SourceID = "paloalto-list"
	PerlDB                SourceID = "perl-db"
	PhotonCVE             SourceID = "photon-cve"
	PhotonOVAL            SourceID = "photon-oval"
	PipDB                 SourceID = "pip-db"
	PipGHSA               SourceID = "pip-ghsa"
	PipGLSA               SourceID = "pip-glsa"
	PipOSV                SourceID = "pip-osv"
	PubGHSA               SourceID = "pub-ghsa"
	PubOSV                SourceID = "pub-osv"
	RDB                   SourceID = "r-db"
	ROSV                  SourceID = "r-osv"
	RedHatCSAF            SourceID = "redhat-csaf"
	RedHatCVE             SourceID = "redhat-cve"
	RedHatCVRF            SourceID = "redhat-cvrf"
	RedHatOSV             SourceID = "redhat-osv"
	RedHatOVALv1          SourceID = "redhat-ovalv1"
	RedHatOVALv2          SourceID = "redhat-ovalv2"
	RedHatVEX             SourceID = "redhat-vex"
	RockyErrata           SourceID = "rocky-errata"
	RockyOSV              SourceID = "rocky-osv"
	RubygemsDB            SourceID = "rubygems-db"
	RubygemsGHSA          SourceID = "rubygems-ghsa"
	RubygemsGLSA          SourceID = "rubygems-glsa"
	RubygemsOSV           SourceID = "rubygems-osv"
	Snort                 SourceID = "snort"
	SUSECSAF              SourceID = "suse-csaf"
	SUSECSAFVEX           SourceID = "suse-csaf-vex"
	SUSECVRF              SourceID = "suse-cvrf"
	SUSECVRFCVE           SourceID = "suse-cvrf-cve"
	SUSEOSV               SourceID = "suse-osv"
	SUSEOVAL              SourceID = "suse-oval"
	SwiftGHSA             SourceID = "swift-ghsa"
	SwiftOSV              SourceID = "swift-osv"
	UbuntuCVE             SourceID = "ubuntu-cve"
	UbuntuNotice          SourceID = "ubuntu-notice"
	UbuntuOSV             SourceID = "ubuntu-osv"
	UbuntuOVAL            SourceID = "ubuntu-oval"
	UbuntuCVETracker      SourceID = "ubuntu-cve-tracker"
	UbuntuUSNDB           SourceID = "ubuntu-usndb"
	VulnCheckKEV          SourceID = "vulncheck-kev"
	WindowsAdvisory       SourceID = "windows-advisory"
	WindowsBulletin       SourceID = "windows-bulletin"
	WindowsCSAF           SourceID = "windows-csaf"
	WindowsCVRF           SourceID = "windows-cvrf"
	WindowsDeployment     SourceID = "windows-deployment"
	WindowsMSUC           SourceID = "windows-msuc"
	WindowsProduct        SourceID = "windows-product"
	WindowsVulnerability  SourceID = "windows-vulnerability"
	WindowsWSUSSCN2       SourceID = "windows-wsusscn2"
	WolfiOSV              SourceID = "wolfi-osv"
	WolfiSecDB            SourceID = "wolfi-secdb"
	WindRiverLinux        SourceID = "wind-river-linux"
)

func (d *Source) Sort() {
	slices.Sort(d.Raws)
}

func Compare(x, y Source) int {
	return cmp.Or(
		cmp.Compare(x.ID, y.ID),
		slices.Compare(x.Raws, y.Raws),
	)
}
