name: Archive-Raw
on:
  workflow_run:
    workflows: [Extract(Nightly)]
    types:
      - completed
  workflow_dispatch:

jobs:
  archive-raw:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "alma-errata"
          - "alma-osv"
          - "alma-oval"
          - "alpine-secdb"
          - "alpine-osv"
          - "amazon"
          - "android-osv"
          - "arch"
          - "attack"
          - "bitnami-osv"
          - "capec"
          - "cargo-ghsa"
          - "cargo-osv"
          # - "cargo-db"
          - "chainguard-osv"
          - "composer-ghsa"
          - "composer-glsa"
          - "composer-osv"
          # - "composer-db"
          - "conan-glsa"
          - "cwe"
          - "debian-osv"
          - "debian-oval"
          - "debian-security-tracker-api"
          - "debian-security-tracker-salsa"
          - "epss"
          - "erlang-ghsa"
          - "erlang-osv"
          - "exploit-exploitdb"
          - "exploit-github"
          - "exploit-inthewild"
          - "exploit-trickest"
          - "fedora"
          - "fortinet-cvrf"
          - "freebsd"
          - "gentoo"
          - "ghactions-osv"
          - "git-osv"
          - "golang-ghsa"
          - "golang-glsa"
          - "golang-osv"
          # - "golang-db"
          # - "golang-vulndb"
          - "haskell-osv"
          - "jvn-feed-detail"
          - "jvn-feed-product"
          - "jvn-feed-rss"
          - "kev"
          - "linux-osv"
          - "maven-ghsa"
          - "maven-glsa"
          - "maven-osv"
          # - "mitre-cvrf"
          # - "mitre-v4"
          - "mitre-v5"
          - "msf"
          - "netbsd"
          - "npm-ghsa"
          - "npm-glsa"
          - "npm-osv"
          # - "npm-db"
          - "nuget-ghsa"
          - "nuget-glsa"
          - "nuget-osv"
          - "nvd-api-cve"
          - "nvd-api-cpe"
          - "nvd-api-cpematch"
          - "nvd-feed-cve"
          - "nvd-feed-cpe"
          - "nvd-feed-cpematch"
          - "oracle"
          - "oss-fuzz-osv"
          # - "perl-db"
          - "pip-ghsa"
          - "pip-glsa"
          - "pip-osv"
          # - "pip-db"
          - "pub-ghsa"
          - "pub-osv"
          - "r-osv"
          - "redhat-cve"
          - "redhat-csaf"
          # - "redhat-cvrf"
          - "redhat-repository-to-cpe"
          # - "redhat-ovalv1"
          - "redhat-ovalv2"
          - "redhat-vex"
          - "redhat-osv"
          - "rocky-errata"
          - "rocky-osv"
          - "rubygems-ghsa"
          - "rubygems-glsa"
          - "rubygems-osv"
          # - "rubygems-db"
          - "snort"
          - "suse-oval"
          - "suse-cvrf"
          - "suse-cvrf-cve"
          - "suse-csaf"
          - "suse-csaf-vex"
          - "suse-osv"
          - "swift-ghsa"
          - "swift-osv"
          - "ubuntu-oval"
          - "ubuntu-cve-tracker"
          - "ubuntu-osv"
          - "vulncheck-kev"
          # - "windows-bulletin"
          - "windows-cvrf"
          - "windows-msuc"
          - "windows-wsusscn2"
          - "wolfi-osv"
    uses: ./.github/workflows/archive.yml
    with:
      type: raw
      target: ${{ matrix.target }}
