name: Archive-Extracted
on:
  workflow_run:
    workflows: [Extract(Nightly)]
    types:
      - completed
  workflow_dispatch:

jobs:
  archive-extracted:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "alma-errata"
          - "alma-osv"
          # - "alma-oval"
          - "alpine-secdb"
          - "alpine-osv"
          - "amazon"
          - "arch"
          # - "debian-osv"
          # - "debian-oval"
          # - "debian-security-tracker-api"
          # - "debian-security-tracker-salsa"
          # - "fedora"
          # - "fortinet"
          # - "fortinet-cvrf"
          - "freebsd"
          # - "gentoo"
          # - "netbsd"
          - "oracle"
          # - "redhat-cve"
          # - "redhat-csaf"
          # - "redhat-cvrf"
          # - "redhat-oval-repository-to-cpe"
          # - "redhat-ovalv1"
          # - "redhat-ovalv2"
          # - "redhat-vex"
          # - "rocky-errata"
          # - "rocky-osv"
          # - "suse-oval"
          # - "suse-cvrf"
          # - "suse-cvrf-cve"
          # - "suse-csaf"
          # - "suse-csaf-vex"
          # - "ubuntu-oval"
          # - "ubuntu-cve-tracker"
          # - "windows-bulletin"
          # - "windows-cvrf"
          # - "windows-msuc"
          # - "windows-wsusscn2"

          # - "cargo-ghsa"
          # - "cargo-osv"
          # - "composer-ghsa"
          # - "composer-glsa"
          # - "composer-osv"
          # - "conan-glsa"
          # - "erlang-ghsa"
          # - "erlang-osv"
          # - "golang-ghsa"
          # - "golang-glsa"
          # - "golang-osv"
          # - "haskell-osv"
          # - "maven-ghsa"
          # - "maven-glsa"
          # - "maven-osv"
          # - "npm-ghsa"
          # - "npm-glsa"
          # - "npm-osv"
          # - "nuget-ghsa"
          # - "nuget-glsa"
          # - "nuget-osv"
          # - "pip-ghsa"
          # - "pip-glsa"
          # - "pip-osv"
          # - "pub-ghsa"
          # - "pub-osv"
          # - "r-osv"
          # - "rubygems-ghsa"
          # - "rubygems-glsa"
          # - "rubygems-osv"
          # - "swift-ghsa"
          # - "swift-osv"

          # - "attack"
          # - "capec"
          # - "cwe"
          - "epss"
          # - "exploit-exploitdb"
          # - "exploit-github"
          # - "exploit-inthewild"
          # - "exploit-trickest"
          # - "jvn-feed-detail"
          # - "jvn-feed-product"
          # - "jvn-feed-rss"
          - "kev"
          # - "mitre-cvrf"
          # - "mitre-v4"
          - "mitre-v5"
          # - "msf"
          # - "nvd-api-cve"
          # - "nvd-api-cpe"
          # - "nvd-feed-cve"
          # - "nvd-feed-cpe"
          # - "snort"
          # - "vulncheck-kev"
          - "eol"
    uses: ./.github/workflows/archive.yml
    with:
      type: extracted
      target: ${{ matrix.target }}
