name: Extract
on:
  workflow_run:
    workflows: [Fetch]
    types:
      - completed
  workflow_dispatch:

jobs:
  extract-main:
    name: extract vuls-data-extracted-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - "alma-errata"
          - "alma-osv"
          # - "alma-oval"
          - "alpine-secdb"
          - "alpine-osv"
          - "amazon"
          - "arch"
          # - "debian-osv"
          # - "debian-oval"
          # - "debian-security-tracker-api"
          # - "debian-security-tracker-salsa"
          # - "fedora"
          # - "fortinet"
          # - "fortinet-cvrf"
          - "freebsd"
          # - "gentoo"
          # - "netbsd"
          - "oracle"
          # - "redhat-cve"
          # - "redhat-csaf"
          # - "redhat-cvrf"
          # - "redhat-ovalv1"
          # - "redhat-ovalv2"
          # - "redhat-vex"
          # - "rocky-errata"
          # - "rocky-osv"
          # - "suse-oval"
          # - "suse-cvrf"
          # - "suse-cvrf-cve"
          # - "suse-csaf"
          # - "suse-csaf-vex"
          # - "ubuntu-oval"
          # - "ubuntu-cve-tracker"
          # - "windows-bulletin"
          # - "windows-cvrf"
          # - "windows-msuc"
          # - "windows-wsusscn2"

          # - "cargo-ghsa"
          # - "cargo-osv"
          # - "composer-ghsa"
          # - "composer-glsa"
          # - "composer-osv"
          # - "conan-glsa"
          # - "erlang-ghsa"
          # - "erlang-osv"
          # - "golang-ghsa"
          # - "golang-glsa"
          # - "golang-osv"
          # - "haskell-osv"
          # - "maven-ghsa"
          # - "maven-glsa"
          # - "maven-osv"
          # - "npm-ghsa"
          # - "npm-glsa"
          # - "npm-osv"
          # - "nuget-ghsa"
          # - "nuget-glsa"
          # - "nuget-osv"
          # - "pip-ghsa"
          # - "pip-glsa"
          # - "pip-osv"
          # - "pub-ghsa"
          # - "pub-osv"
          # - "r-osv"
          # - "rubygems-ghsa"
          # - "rubygems-glsa"
          # - "rubygems-osv"
          # - "swift-ghsa"
          # - "swift-osv"

          # - "cwe"
          # - "capec"
          # - "attack"
          - "epss"
          # - "exploit-exploitdb"
          # - "exploit-github"
          # - "exploit-inthewild"
          # - "exploit-trickest"
          # - "jvn-feed-detail"
          # - "jvn-feed-product"
          # - "jvn-feed-rss"
          - "kev"
          # - "mitre-cvrf"
          # - "mitre-v4"
          - "mitre-v5"
          # - "msf"
          # - "nvd-api-cpe"
          # - "nvd-feed-cve"
          # - "nvd-feed-cpe"
          # - "nvd-feed-cpematch"
          # - "snort"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: go install
        run: go install ./cmd/vuls-data-update

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: vulsio
          repositories: "vuls-data-extracted-${{ matrix.target }}"

      - name: Check out raw repository
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-raw-${{ matrix.target }}
          path: vuls-data-raw-${{ matrix.target }}

      - name: Check out extracted repository
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-extracted-${{ matrix.target }}
          path: vuls-data-extracted-${{ matrix.target }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Extract
        run: vuls-data-update extract ${{ matrix.target }} --dir vuls-data-extracted-${{ matrix.target }} vuls-data-raw-${{ matrix.target }}

      - name: Split Large Files
        run: find vuls-data-extracted-${{ matrix.target }} -name "*.json" -size +50M | xargs -I {} sh -c "split -a 3 -d -b 50m {} {}. && rm {}"

      - name: set Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push
        run: |
          cd vuls-data-extracted-${{ matrix.target }}
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update"
            git push
          fi

      - name: Check github repository size
        run: |
          SIZE=$(curl -s https://api.github.com/repos/vulsio/vuls-data-extracted-${{ matrix.target }} | jq '.size')
          echo "repository size [KB]:" ${SIZE}
          if [ ${SIZE} -gt 9500000 ]; then
            echo "### Repository size is *over 9.5 GB*. Archive it!"

            (
              echo "### Repository size is *over 9.5 GB*. Archive it!"
              echo ""
              echo "### 1. Fork & archive the repository:"
              echo ""
              echo "\`\`\`"
              echo "gh repo fork vulsio/vuls-data-extracted-${{ matrix.target }} --clone=false --org=vulsio --fork-name=vuls-data-extracted-${{ matrix.target }}-archive-<ARCHIVE-NUMBER>"
              echo "gh repo archive vulsio/vuls-data-extracted-${{ matrix.target }}-archive-<ARCHIVE-NUMBER> --yes"
              echo "\`\`\`"
              echo "" 
              echo "### 2. Delete all commits and add one with the latest contents:"
              echo ""
              echo "\`\`\`"
              echo "git clone git@github.com:vulsio/vuls-data-extracted-${{ matrix.target }}.git"
              echo "cd vuls-data-extracted-${{ matrix.target }}"
              echo "git checkout --orphan latest-only"
              echo "git add -A"
              echo "git commit -m 'just archived' > /dev/null"
              echo "git branch -D main"
              echo "git branch -m main"
              echo "git push --force origin main"
              echo "\`\`\`"
              echo ""
            ) >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

  extract-nvd-api-cve:
    name: extract vuls-data-extracted-nvd-api-cve
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: go install
        run: go install ./cmd/vuls-data-update

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: vulsio
          repositories: "vuls-data-extracted-nvd-api-cve"

      - name: Check out raw repository, CVE
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-raw-nvd-api-cve
          path: vuls-data-raw-nvd-api-cve

      - name: Check out raw repository, CPEMATCH
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-raw-nvd-api-cpematch
          path: vuls-data-raw-nvd-api-cpematch

      - name: Check out extracted repository
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-extracted-nvd-api-cve
          path: vuls-data-extracted-nvd-api-cve
          token: ${{ steps.app-token.outputs.token }}

      - name: Extract
        run: vuls-data-update extract nvd-api-cve --dir vuls-data-extracted-nvd-api-cve vuls-data-raw-nvd-api-cve vuls-data-raw-nvd-api-cpematch

      - name: Split Large Files
        run: find vuls-data-extracted-nvd-api-cve -name "*.json" -size +50M | xargs -I {} sh -c "split -a 3 -d -b 50m {} {}. && rm {}"

      - name: set Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push
        run: |
          cd vuls-data-extracted-nvd-api-cve
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update"
            git push
          fi

      - name: Check github repository size
        run: |
          SIZE=$(curl -s https://api.github.com/repos/vulsio/vuls-data-extracted-nvd-api-cve | jq '.size')
          echo "repository size [KB]:" ${SIZE}
          if [ ${SIZE} -gt 9500000 ]; then
            echo "### Repository size is *over 9.5 GB*. Archive it!"

            (
              echo "### Repository size is *over 9.5 GB*. Archive it!"
              echo ""
              echo "### 1. Fork & archive the repository:"
              echo ""
              echo "\`\`\`"
              echo "gh repo fork vulsio/vuls-data-extracted-nvd-api-cve --clone=false --org=vulsio --fork-name=vuls-data-extracted-nvd-api-cve-archive-<ARCHIVE-NUMBER>"
              echo "gh repo archive vulsio/vuls-data-extracted-nvd-api-cve-archive-<ARCHIVE-NUMBER> --yes"
              echo "\`\`\`"
              echo "" 
              echo "### 2. Delete all commits and add one with the latest contents:"
              echo ""
              echo "\`\`\`"
              echo "git clone git@github.com:vulsio/vuls-data-extracted-nvd-api-cve.git"
              echo "cd vuls-data-extracted-nvd-api-cve"
              echo "git checkout --orphan latest-only"
              echo "git add -A"
              echo "git commit -m 'just archived' > /dev/null"
              echo "git branch -D main"
              echo "git branch -m main"
              echo "git push --force origin main"
              echo "\`\`\`"
              echo ""
            ) >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

  extract-eol:
    name: extract vuls-data-extracted-eol
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: go install
        run: go install ./cmd/vuls-data-update

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: vulsio
          repositories: "vuls-data-extracted-eol"

      - name: Check out extracted repository
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-extracted-eol
          path: vuls-data-extracted-eol
          token: ${{ steps.app-token.outputs.token }}

      - name: Extract
        run: vuls-data-update extract eol --dir vuls-data-extracted-eol

      - name: Split Large Files
        run: find vuls-data-extracted-eol -name "*.json" -size +50M | xargs -I {} sh -c "split -a 3 -d -b 50m {} {}. && rm {}"

      - name: set Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push
        run: |
          cd vuls-data-extracted-eol
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update"
            git push
          fi

      - name: Check github repository size
        run: |
          SIZE=$(curl -s https://api.github.com/repos/vulsio/vuls-data-extracted-eol | jq '.size')
          echo "repository size [KB]:" ${SIZE}
          if [ ${SIZE} -gt 9500000 ]; then
            echo "### Repository size is *over 9.5 GB*. Archive it!"

            (
              echo "### Repository size is *over 9.5 GB*. Archive it!"
              echo ""
              echo "### 1. Fork & archive the repository:"
              echo ""
              echo "\`\`\`"
              echo "gh repo fork vulsio/vuls-data-extracted-eol --clone=false --org=vulsio --fork-name=vuls-data-extracted-eol-archive-<ARCHIVE-NUMBER>"
              echo "gh repo archive vulsio/vuls-data-extracted-eol-archive-<ARCHIVE-NUMBER> --yes"
              echo "\`\`\`"
              echo "" 
              echo "### 2. Delete all commits and add one with the latest contents:"
              echo ""
              echo "\`\`\`"
              echo "git clone git@github.com:vulsio/vuls-data-extracted-eol.git"
              echo "cd vuls-data-extracted-eol"
              echo "git checkout --orphan latest-only"
              echo "git add -A"
              echo "git commit -m 'just archived' > /dev/null"
              echo "git branch -D main"
              echo "git branch -m main"
              echo "git push --force origin main"
              echo "\`\`\`"
              echo ""
            ) >> $GITHUB_STEP_SUMMARY

            exit 1
          fi
