name: Log Push to Main
run-name: "#${{ github.run_number }} | ${{ github.sha }} | forced:${{ github.event.forced }} | @${{ github.actor }}"

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  log:
    runs-on: ubuntu-slim
    steps:
      - name: Log push event
        run: echo "Push detected."
