name: Update vuls-data
on:
  workflow_dispatch:

jobs:
  fetch:
    name: fetch vuls-data-test
    runs-on: ubuntu-latest
    steps:
      - name: set Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Check out fetch data repository
        uses: actions/checkout@v4
        with:
          repository: vulsio/vuls-data-raw-test
          path: $HOME/vuls-data-raw-test

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        # with:
          # token: ${{ secrets.GH_PAT }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: go install
        run: go install ./cmd/vuls-data-update

      - name: fetch test
        run: |
          vuls-data-update fetch arch --dir $HOME/vuls-data-test
          cd $HOME/vuls-data-test
          git commit --allow-empty -am "update arch"
          git push origin HEAD:main
          cd ..
